sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
notifications:
  email:
    recipients:
      - craig@nunemakerllc.com
    on_success: never
    on_failure: always
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install autoconf-archive"
  - "sudo apt-get -y install autoconf"
  - "sudo apt-get -y install autotools-dev"
  - "sudo apt-get -y install pkg-config"
  - "autoreconf --install --force"
script:
  - mkdir build
  - cd build
  - "../configure"
  - make
  - make dist
